sudo: true
language: java
install: travis_wait mvn install
jdk: oraclejdk8
env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
  
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
